server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  main:
    allow-circular-references: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: root
    password: 1111

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 828005429821-84tklte7vs32oa7iiku8d4ra1ds33bi3.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
            
          facebook:
            client-id: 3239041736363611
            client-secret: 715892905fd2c2a5a1bcaee7e068b261
            scope:
            - email
            - public_profile
          
          kakao:
            client-id: b870e06a874e4ded1295c2e12a932f86
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope:
            - profile_nickname
            - account_email
                        
          naver:
            client-id: WhGYVuA7FiqogrZNBaKf
            client-secret: ufAVN5s1PV
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope:
            - name
            - email
            
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize 
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키 값으로 네이버가 리턴해줌
            
mybatis:
  mapper-locations: sqlmap/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.cos.security1.model